### ISSUE TITLE
Arrange content in drive for Library publishing

### ISSUE THREAD

**Issue by thebestsophist** [covid19-guide/project-tracking#10]
# Description
We need to organize this in a way that makes Library happy

# Slack Channel
covid-guide

# Supporting docs
- [public folder](https://drive.google.com/open?id=1OQE5ZZU3E3lQYWoh_9gJRE3YaEcxRXZt)
- [working folder](https://drive.google.com/open?id=1Db55Mnh_AnK_x8FAt68HZXbtGoe32LZN)

**Comment by knowtheory** [comment]
We got it sorted! see https://drive.google.com/drive/folders/1cJkbWxScgo8Gf5Y___yhd_GRGg0l02QO
