### ISSUE TITLE
Image hosting

### ISSUE THREAD

**Issue by thebestsophist** [covid19-guide/project-tracking#11]
# Description
For the site.

# Slack Channel
covid-guide

**Comment by knowtheory** [comment]
We can just tell the repo that it's a github pages site, and then we can use it for image hosting innit.

**Comment by knowtheory** [comment]
My thought on this is basically that we can have master for the current dev branch, and then we can have a `gh-pages` branch which is public/production.

**Comment by ryanpitts** [comment]
_Love_ the idea of using `gh-pages` to get image hosting. I do feel a little bit weird about a dev branch called `master`—maybe just rename to `dev`?

**Comment by ryanpitts** [comment]
OK this is set up, we have a `master` set up as the production branch in https://github.com/covid19-guide/covid-19-guide-for-journalists

Assets there are currently available at URLs like so: https://covid19-guide.github.io/covid-19-guide-for-journalists/assets/logo.svg

(Once we have the site working at the real domain, we should be able to set up a custom domain for serving these files as well so CSS paths are a little less messy.)

**Comment by knowtheory** [comment]
![guide logo](https://covid19-guide-assets.ops.guide/assets/logo.svg)

working!
