### ISSUE TITLE
Broken twitter link for Lindsay Muscato in "the team" section

### ISSUE THREAD

**Issue by ebaebaeba** [covid19-guide/project-tracking#31]
# Description
Twitter link for Lindsay is broken, just has the username (lmuscato) but should be full link: https://twitter.com/lmuscato

# Slack Channel
n/a

# Supporting docs
- https://covid19.ops.guide/about-the-project#h.jvh1qujdv6xq

**Comment by ryanpitts** [comment]
Fixed! thank you!
