### ISSUE TITLE
Add people to the Library customization repository

### ISSUE THREAD

**Issue by thebestsophist** [covid19-guide/project-tracking#6]
# Description
@tinabeans needs to add folks to the github repo for customizing our instance of Library

# Slack Channel
covid-guide

**Comment by tinabeans** [comment]
Just Ted and Ryan?

**Comment by thebestsophist** [comment]
@tinabeans yup!

**Comment by knowtheory** [comment]
I've updated and made some changes to the customization repo.

it's been renamed to [`covid19-guide-styles`](https://github.com/covid19-guide/covid19-guide-styles) (so apologies if i've broken anybody's github repos)

Also, i've added the repo to the core team's permissions.
